"""Add firmware_version and enabled to device

Revision ID: fae56d96855c
Revises: c937257e2e19
Create Date: 2026-07-09 15:38:53.939847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae56d96855c'
down_revision = 'c937257e2e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('firmware_version', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('firmware_version')
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
