name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv pip install -r requirements.txt pytest-xdist

      - name: Run Tests
        run: uv run --with pytest-xdist pytest tests/ -v --tb=short -n auto --durations=5
        env:
          SECRET_KEY: test-key
